baseURL: "https://srikanthperinkulam.com/"
title: Srikanth Perinkulam
paginate: 10
theme: PaperMod

rssLimit: 15
ignoreLogs: ['warning-goldmark-raw-html']
enableRobotsTXT: false
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Srikanth Perinkulam
  description: "Mountains, family, privacy and everything else"
  keywords: [Blog, Portfolio, PaperMod]
  author:
    name: Srikanth Perinkulam
    nick: SSP
    email: ssphugo@srkn.anonaddy.com
  # author: ["Me", "You"] # multiple authors
  images: ["/images/favicon/apple-touch-icon.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowFullTextinRSS: true
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  social: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Srikanth Perinkulam"
#    icon: /images/favicon/apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: Srikanth Perinkulam
    subtitle:
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
#    Title: "Hi there \U0001F44B"
#    Content: Welcome to my blog

  socialIcons:
    - name: "rss"
      url: "https://srikanthperinkulam.com/index.xml"
#    - name: x
#      url: "https://x.com/"
#    - name: stackoverflow
#      url: "https://stackoverflow.com"
#    - name: github
#      url: "https://github.com/"

  analytics:
#    google:
#      SiteVerificationTag: "XYZabc"
#    bing:
#      SiteVerificationTag: "XYZabc"
#    yandex:
#      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
#    URL: "https://github.com/<path_to_repo>/content"
#    Text: "Suggest Changes" # edit text
#    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
absoluteURLs: true
outputFormats:
  RSS:
    Permalinkable: true
  JSOn:
    Permalinkable: true

menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20
    - identifier: rewind
      name: Rewind
      url: /rewind/
      weight: 20
    - identifier: micro
      name: Micro
      url: /micro/
      weight: 20
    - identifier: photos
      name: Photos
      url: /photos/
      weight: 20
    - identifier: now
      name: Now
      url: /now/
      weight: 20
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 30
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 40
#    - identifier: example
#      name: example.org
#      url: https://example.org
#      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

taxonomies:
  category: categories
  tag: tags
  year: year
  month: month
  date: date

permalinks:
  posts: "/:year/:month/:day/:title"
